#!/usr/bin/env python3
#
# Copyright (C) 2017 Linaro Limited
# Author: Matt Hart <matthew.hart@linaro.org>
#
# Copyright (C) 2017, 2018 Collabora Ltd
# Author: Guillaume Tucker <guillaume.tucker@collabora.com>
#
# This module is free software; you can redistribute it and/or modify it under
# the terms of the GNU Lesser General Public License as published by the Free
# Software Foundation; either version 2.1 of the License, or (at your option)
# any later version.
#
# This library is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more
# details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this library; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA

"""Create a new lab entry."""

import requests
import sys
import kci_admin.lab


def main(argv):
    parser = kci_admin.lab.parser_create()
    args = parser.parse_args(argv)
    opts = {o: getattr(args, o) for o in
            ['lab_name', 'first_name', 'last_name', 'email']}
    url, headers, data = kci_admin.lab.request_create(args.host, opts)

    if args.dry:
        print("Dry run - not sending any request")
        print("URL: {}".format(url))
        print(headers)
        print(data)
    else:
        response = requests.post(url, headers=headers, data=data)
        print("Response:")
        print(response.content)


if __name__ == "__main__":
    main(sys.argv[1:])
